config/routes.rb
Rails.application.routes.draw do
	resources :users
	resources :doctors
	resources :home
	resources :sessions
	resources :messages
	resources :patients

get "/logout", to: "sessions#destroy"
end

app/models/affiliation.rb
class Affiliation < ActiveRecord::Base
	belongs_to :hospital	
	belongs_to :doctor

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
	belongs_to :hospital	
	belongs_to :affiliations
	belongs_to :TypeofDoctor	
	has_many :messages

	validates :name, presence: true
  	validates :dob, presence: true
  	validates :education, presence: true
  	validates :specialty, presence: true
end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
	has_many :affliations
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  validates :body, presence: true
  belongs_to :doctor
  belongs_to :patient

end

app/models/patient.rb
class Patient < ActiveRecord::Base
	belongs_to :hospital	
	belongs_to :affiliations
	belongs_to :doctor

	has_many :messages	

end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/models/typeof_doctor.rb
class TypeofDoctor < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true
  validates :password, presence: true
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :exception
  before_action :auth

helper_method :current_user
before_action :auth

  def auth
  	if current_user
  	else
  	  redirect_to new_session_url
  	end	
  end

  def current_user
	User.find_by(id: session["user_id"])
  end

end

app/controllers/concerns/doctors_controller.rb
class DoctorsController < ApplicationController

  def index
    @doctors = Doctors.all
  end

  def new
    @doctors = Doctors.new
  end

  def create
  	Doctors.create(params["doctors"])
   	redirect_to doctors_url
  end

  def edit
  	@doctors = Doctors.find_by(id: params["id"])
  end

  def update
  	@doctors = Doctors.find_by(id: params["id"])
  	@doctors.update(params["doctors"])
  	redirect_to doctors_url
  end

  def destroy
  	@doctor = Doctors.find_by(id: params["id"])
  	@doctor.delete
	redirect_to doctors_url
  end	
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
skip_before_action :auth, only: [:new, :create]

  def index
  @doctors = Doctor.all
  end

  def show 
  @doctor = Doctor.find_by(id: params["id"])  
  @message = Message.new
  @messages = Message.all

  end

  def new
  @doctor = Doctor.new
  end
 
  def create
    @User = User.new 
    @User.email = params["email"]
    @User.password = params["password"]
    @User.save!

    @Doctor = Doctor.new
    @Doctor.name = params["doctor"]["name"]
    @Doctor.dob = params["doctor"]["dob"]
    @Doctor.education = params["doctor"]["education"]
    @Doctor.years_of_experience = params["doctor"]["years_of_experience"]
    @Doctor.specialty = params["doctor"]["specialty"]
    @Doctor.typeofdoctor_id = params["doctor"]["typeofdoctor_id"]
    @Doctor.hospital_id = params["doctor"]["hospital_id"]
    @Doctor.user_id = @User.id
    @Doctor.save!
  	
   	redirect_to doctor_url(@Doctor)
  end

  def edit
  	@doctor = Doctor.find_by(id: params["id"])
  end

  def update
  	@doctor = Doctor.find_by(id: params["id"])
  	@doctor.update(params["doctor"])
  	redirect_to doctors_url
  end

  def destroy
  	@doctor = Doctor.find_by(id: params["id"])
  	@doctor.delete
	redirect_to doctors_url
  end	

end




  

app/controllers/home_controller.rb
class HomeController < ApplicationController
skip_before_action :auth

def index
end

def show
end

def new
  @user = User.new
end

def create
 doctor_params = params.require(:doctor).permit(:name, :email, :password, :doctortype)
  @doctor = Doctor.create(doctor_params)
  if @doctor.valid?
    session["doctor_id"] = @doctor.id
    redirect_to "/doctors/"

  else
    render "/doctors/"
  end
end

end 

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

def index
  @message = Message.all
  end

  def show 
  @message = Message.find_by(id: params["message"])  
  @Doctor = Doctor.find_by(user_id: current_user.id)
    
    @message.doctor = @Doctor
    @message.user = current_user

  @message = Message.find_by(id: params["message"]) 
  @Patient = Patient.find_by(user_id: current_user.id)
    
    @message.patient = @Patient
    @message.user = current_user

  end

  def new
  @message = Message.new
  end
    
  def create
  @message = Message.new(params["message"])
  @Doctor = Doctor.find_by(user_id: current_user.id)

    @message.doctor = @Doctor
    @message.user = current_user
    
    if @message.save!
        redirect_to doctor_url(@Doctor)

    else
      render "new"
    end
    
  end

  def destroy
    @message = Message.find_by(id: params["id"])
    @message.delete
  redirect_to message_url
  end 
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
skip_before_action :auth, only: [:new, :create]

  def index
  @patients = Patient.all
  end

  def show 
  @patient = Patient.find_by(id: params["id"])  
  @message = Message.new
  @messages = Message.all

  end

  def new
  @patient = Patient.new
  end
    
  def create
    @User = User.new 
    @User.email = params["email"]
    @User.password = params["password"]
    @User.save!

    @Patient= Patient.new
    @Patient.name = params["patient"]["name"]
    @Patient.dob = params["patient"]["dob"]
    @Patient.diagnosis = params["patient"]["diagnosis"]
    @Patient.symptoms = params["patient"]["symptoms"]
    @Patient.level_of_pain = params["patient"]["level_of_pain"]
    @Patient.hospital_id = params["patient"]["hospital_id"]
    @Patient.doctor_id = params["patient"]["doctor_id"]
    @Patient.user_id = @User.id
    @Patient.save!

    redirect_to patients_url
  end

  def edit
    @patient = Patient.find_by(id: params["id"])
  end

  def update
    @patient = Patient.find_by(id: params["id"])
    @patient.update(params["patient"])
    redirect_to patients_url
  end

  def destroy
    @patient = Patient.find_by(id: params["id"])
    @patient.delete
  redirect_to patients_url
  end 

end




  

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout false
  skip_before_action :auth
  def create
    # Do authentication
    user = User.find_by(email: params["email"])
    if user && user.authenticate(params["password"])
      session["user_id"] = user.id
      if @Doctor = Doctor.find_by(user_id: user.id)
        redirect_to doctor_url(@Doctor)
    
    # if @Doctor = Doctor.find_by(user_id: user.id)
    #   redirect_to doctor_url(@Doctor)
    
      else
        @Patient = Patient.find_by(user_id: user.id)
        redirect_to patient_url(@Patient)
      end
 
    else
      redirect_to new_session_path, alert: "Bad username or password"
    end
  end

  def destroy
    session["user_id"] = nil
    redirect_to new_session_path, notice: "You are logged out."
  end
end

app/controllers/user_controller.rb
class UsersController < ApplicationController

  def new
  @user = User.new
  end
  	
  def create
  	
     @user = User.create(params["user"])
    if @user.valid?
      @doctor=Doctor.create
      @user.doctor_id=@doctor.id
      @doctor.name = @user.name 
      @doctor.save
      redirect_to doctors_path
    else
      render "new"
    end
  end

end




  

app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_action :auth
  def new
  @user = User.new
  end
  	
  def create
  	
     @user = User.create(name: params["user"]) 
    if @user.valid?
      @doctor=Doctor.create
      @user.doctor_id=@doctor.id
      @doctor.name = @user.name 
      @doctor.save
      redirect_to home_index_path
    else
      render "new"
    end
  end

end





  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/doctors/edit.html.erb
<%= form_for @doctor do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
    <%= form.label :dob %>
    <%= form.text_field :dob, class: "form-control" %>
    <%= form.label :education %>
    <%= form.text_field :education, class: "form-control" %>
    <%= form.label :years_of_experience %>
    <%= form.text_field :years_of_experience, class: "form-control" %>
    <%= form.label :specialty %>
    <%= form.text_field :specialty, class: "form-control" %>
    <%= form.label :typeofdoctor_id %>
    <%= form.collection_select :typeofdoctor_id, class: "form-control" %>
    <%= form.label :hospital_id %>
    <%= form.collection_select :hospital_id, Hospital.all, :id, :name %>
  </div>
  <%= form.button 'Update Doctor', class: "btn btn-success" %>
<% end %>

app/views/doctors/index.html.erb
<h3>Welcome to the CareLog for Doctors!</h3>

<% @doctors.each do |doctor|%>
	<p>
<%= link_to doctor.name, doctor_url(doctor)%>
<%= link_to "Edit", edit_doctor_url(doctor)%> 
<%= link_to "Delete", doctor_url(doctor), method: :delete%>
	</p>

<% end %>

<%= link_to "New Doctor", new_user_path, class: 'btn btn-sm btn-success' %>

app/views/doctors/new.html.erb
<%= form_for @doctor do |form| %>
  <div class="form-group">
    <p>
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </p>
    <p>
      <%= form.label :dob %>
      <%= form.text_field :dob, class: "form-control" %>
    </p>

    <p>
      <%= form.label :education %>
      <%= form.text_field :education, class: "form-control" %>
    </p>

    <p>
      <%= form.label :years_of_experience %>
      <%= form.text_field :years_of_experience, class: "form-control" %>
    </p>

    <p>
      <%= form.label :specialty %>
      <%= form.text_field :specialty, class: "form-control" %>
    </p>

    <p>
      <%= form.label :typeofdoctor_id %>
      <%= form.text_field :typeofdoctor_id, class: "form-control" %>
    </p>

    <p>
      <%= form.label :hospital_id %>
      <%= form.collection_select :hospital_id, Hospital.all, :id, :name %>
    </p>

    <p>
      <label for="email">Email</label>
      <%= text_field_tag :email, "", class: "form-control" %>
    </p>

    <p>
      <label for="password">Password</label>
      <%= text_field_tag :password, "", class: "form-control" %>
    </p>

  </div>
  
  <p><%= form.button 'Create Doctor', class: "btn btn-success" %></p>
<% end %>

app/views/doctors/show.html.erb
<%= form_for @message do |form| %>
  <div class="form-group">
    <p>
      <%= form.label :body, "Message" %>
      <%= form.text_area :body, class: "form-control" %>
    </p>

<p><%= form.button 'Submit Message', class: "btn btn-success" %></p>
<% end %>
  
<div class="row">
  <div class="col-md-7 col-md-offset-3">
    <h3>Current Messages</h3>
    <% @messages.each do |message| %>
    	<% if message.doctor_id == @doctor.id %>
    	<p><%= message.body %></p>
    <% end %>
    <% end %>
      <h4>
         
     
       
    

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CareLog | Patient Data Tracking App</title>
    <!-- Logo Font -->
    <link href="http://fonts.googleapis.com/css?family=Luckiest+Guy" rel="stylesheet" type="text/css">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
<body>

  <div class="container">

      <!-- Alerts -->
      <% if notice %>
      <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= notice %></div>
      <% end %>
      <% if alert %>
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= alert %></div>
      <% end %>
  </div>

   <div class="container">

<div class="jumbotron">
      <%= image_tag("careloglogo.jpg") %>
      <div class="pull-right"><%= image_tag("femaledoctor.jpg", size: "400x400") %></div>
    <h1>CareLog</h1> 
  <p>Patient Data Tracking Application</p>

  <!-- Link to Doctor Edit Page-->
  <!-- Link to Patient Edit Page-->
    <p> <%=link_to "Log In", new_session_url, class:"btn btn-primary btn-lg" %></p>

</div>
<div class="panel panel-default">
  <div class="panel-body">
<blockquote>
  <p>A doctor's time is valuable. Use our service to make your appointments more efficient.</p>
  <footer>The CareLog Team</footer>
</blockquote>
</div>
</div>

</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Final</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
    <li><%= link_to "Logout", logout_url %></li>
<% end %>

<%= yield %>

</body>
</html>

app/views/messages/index.html.erb
<h3>Here are your messages!</h3>

<% @messages.each do |message|%>
	<p>
<%= link_to doctor.name, doctor_url(doctor)%>
<%= link_to "Edit", edit_doctor_url(doctor)%> 
<%= link_to "Delete", doctor_url(doctor), method: :delete%>
	</p>

<% end %>

<%= link_to "New Doctor", new_user_path, class: 'btn btn-sm btn-success' %>

app/views/messages/new.html.erb
<%= form_for @message do |form| %>
  <div class="form-group">
    <%= form.label :message %>
    <%= form.text_field :message, class: "form-control" %>

  </div>
  
  <p><%= form.button 'New Message', class: "btn btn-success" %></p>
<% end %>

app/views/messages/show.html.erb
<% message = Message.find_by(id: params["id"])%>

app/views/patients/edit.html.erb
<%= form_for @patient do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
    <%= form.label :dob %>
    <%= form.text_field :dob, class: "form-control" %>
    <%= form.label :diagnosis %>
    <%= form.text_field :diagnosis, class: "form-control" %>
    <%= form.label :symptoms %>
    <%= form.text_field :symptoms, class: "form-control" %>
    <%= form.label :level_of_pain %>
    <%= form.text_field :level_of_pain, class: "form-control" %>
    <%= form.label :notes %>
    <%= form.text_field :notes, class: "form-control" %>
    <%= form.label :hospital_id %>
    <%= form.collection_select :hospital_id, Hospital.all, :id, :name %>
    <%= form.label :doctor_id %>
    <%= form.collection_select :doctor_id, Doctor.all, :id, :name %>
  </div>
  <%= form.button 'Update Patient', class: "btn btn-success" %>
<% end %>

app/views/patients/index.html.erb
<h3>Welcome to the Patient Registry</h3>

<% @patients.each do |patient|%>
	<p>
<%= link_to patient.name, patient_url(patient)%>
<%= link_to "Edit", edit_patient_url(patient)%> 
<%= link_to "Delete", patient_url(patient), method: :delete%>
	</p>

<% end %>

<%= link_to "New Patient", new_patient_path, class: 'btn btn-sm btn-success' %>

app/views/patients/new.html.erb
<%= form_for @patient do |form| %>
  <div class="form-group">
    <p>
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </p>
    <p>
      <%= form.label :dob %>
      <%= form.text_field :dob, class: "form-control" %>
    </p>

    <p>
      <%= form.label :diagnosis %>
      <%= form.text_field :diagnosis, class: "form-control" %>
    </p>

    <p>
      <%= form.label :symptoms %>
      <%= form.text_field :symptoms, class: "form-control" %>
    </p>

    <p>
      <%= form.label :level_of_pain %>
      <%= form.text_field :level_of_pain, class: "form-control" %>
    </p>

    <p>
      <%= form.label :notes %>
      <%= form.text_field :notes  , class: "form-control" %>
    </p>

    <p>
      <%= form.label :hospital_id %>
      <%= form.collection_select :hospital_id, Hospital.all, :id, :name %>
    </p>

     <p>
      <%= form.label :doctor_id %>
      <%= form.collection_select :doctor_id, Doctor.all, :id, :name %>
    </p>

      <p>
      <label for="email">Email</label>
      <%= text_field_tag :email, "", class: "form-control" %>
    </p>

    <p>
      <label for="password">Password</label>
      <%= text_field_tag :password, "", class: "form-control" %>
    </p>
  </div>
  
  <p><%= form.button 'Create Patient', class: "btn btn-success" %></p>
<% end %>

app/views/patients/show.html.erb
<%= form_for @message do |form| %>
  <div class="form-group">
    <p>
      <%= form.label :body, "Message" %>
      <%= form.text_area :body, class: "form-control" %>
    </p>

<p><%= form.button 'Submit Message', class: "btn btn-success" %></p>
<% end %>
  
<div class="row">
  <div class="col-md-7 col-md-offset-3">
    <h3>Current Messages</h3>
    <% @messages.each do |message| %>
    	<% if message.patient_id == @patient.id %>
    	<p><%= message.body %></p>
    <% end %>
    <% end %>
      <h4>
         

app/views/users/new.html.erb
<%= form_for @user do |form| %>
  <div class="form-group">
    <p>
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </p>
    <p>
      <%= form.label :email %>
      <%= form.text_field :email, class: "form-control" %>
    </p>

    <p>
      <%= form.label :password %>
      <%= form.text_field :password, class: "form-control" %>
    </p>

  </div>
  
  <p><%= form.button 'Create Doctor', class: "btn btn-success" %></p>
  <p><%= form.button 'Create Patient', class: "btn btn-success" %></p>
<% end %>